import localFont from "next/font/local";
import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import { LoginProvider } from "@/core/context/LoginContext";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import Header from "@/components/modules/header/Header";
import Footer from "@/components/modules/footer/Footer";
import HamburgerMenuProvider from "@/core/context/HamburgerMenuContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HamburgerMenuProvider>
          <LoginProvider>
            <TanstackQueryProvider>
              <Header />
              {children}
              <ToastContainer
                position="top-right"
                autoClose={10000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={true}
                pauseOnFocusLoss
                draggable
                pauseOnHover
              />
              <Footer />
            </TanstackQueryProvider>
          </LoginProvider>
        </HamburgerMenuProvider>
      </body>
    </html>
  );
}
